# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ github_actions ]
  pull_request:
    branches: [ github_actions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Install FDB server and client
      run: |
        wget https://www.foundationdb.org/downloads/6.2.15/ubuntu/installers/foundationdb-clients_6.2.15-1_amd64.deb
        wget https://www.foundationdb.org/downloads/6.2.15/ubuntu/installers/foundationdb-server_6.2.15-1_amd64.deb
        sudo dpkg -i foundationdb-clients_6.2.15-1_amd64.deb foundationdb-server_6.2.15-1_amd64.deb

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct